/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.axesoft.jaxos.app;

import io.netty.bootstrap.Bootstrap;
import io.netty.buffer.Unpooled;
import io.netty.channel.*;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.SocketChannel;
import io.netty.channel.socket.nio.NioSocketChannel;
import io.netty.handler.codec.http.*;
import io.netty.util.CharsetUtil;

import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;

public class ClientApp {
    private static final String DEFAULT_URL = "http://localhost:8081";
    private static final int PAR_FACTOR = 8;

    public static void main(String[] args) throws Exception {
        ClientApp app = new ClientApp();
        String url = (args != null && args.length > 0)? args[0] : DEFAULT_URL;
        app.run(url);
    }

    private HttpRequest request;
    private int n = 2000;
    private long start = 0;
    private AtomicInteger count = new AtomicInteger(0);

    private HttpRequest createRequest(URI uri, String host) {
        HttpRequest request = new DefaultFullHttpRequest(
                HttpVersion.HTTP_1_1, HttpMethod.POST, uri.getRawPath(), Unpooled.EMPTY_BUFFER);
        request.headers().set(HttpHeaderNames.HOST, host);
        request.headers().set(HttpHeaderNames.CONNECTION, HttpHeaderValues.KEEP_ALIVE);
        request.headers().set(HttpHeaderNames.ACCEPT_ENCODING, HttpHeaderValues.TEXT_PLAIN);

        return request;
    }

    public void run(String url) throws Exception {
        URI uri = new URI(url);
        String host = uri.getHost() == null? "127.0.0.1" : uri.getHost();
        int port = uri.getPort();

        this.request = createRequest(uri, host);

        // Configure the client.
        EventLoopGroup group = new NioEventLoopGroup();
        try {
            Bootstrap b = new Bootstrap();
            b.group(group)
                    .channel(NioSocketChannel.class)
                    .handler(new HttpSnoopClientInitializer());

            List<Channel> channels = new ArrayList<>();
            for(int i = 0; i < PAR_FACTOR; i++) {
                // Make the connection attempt.
                Channel ch = b.connect(host, port).sync().channel();
                channels.add(ch);
            }
            // Prepare the HTTP request.

            this.start = System.nanoTime();

            for(Channel ch : channels) {
                // Send the HTTP request.
                ch.writeAndFlush(request);
            }

            for(Channel ch: channels ) {
                // Wait for the server to close the connection.
                ch.closeFuture().sync();
            }

            double millis = (System.nanoTime() - start) / 1e+6;
            double qps = n / (millis/1000.0);
            System.out.println(String.format("POST %d in %.3f millis, QPS is %.0f", n, millis, qps));

        } finally {
            // Shut down executor threads to exit.
            group.shutdownGracefully();
        }
    }

    public class HttpSnoopClientInitializer extends ChannelInitializer<SocketChannel> {

        @Override
        public void initChannel(SocketChannel ch) {
            ChannelPipeline p = ch.pipeline();
            p.addLast(new HttpClientCodec());
            // Remove the following line if you don't want automatic content decompression.
            p.addLast(new HttpContentDecompressor());
            // Uncomment the following line if you don't want to handle HttpContents.
            //p.addLast(new HttpObjectAggregator(1048576));
            p.addLast(new HttpSnoopClientHandler());
        }
    }

    public class HttpSnoopClientHandler extends SimpleChannelInboundHandler<HttpObject> {

        @Override
        public void channelRead0(ChannelHandlerContext ctx, HttpObject msg) {
            if (msg instanceof HttpResponse) {
                HttpResponse response = (HttpResponse) msg;

                //System.err.println("STATUS: " + response.status());
            }
            if (msg instanceof HttpContent) {
                HttpContent content = (HttpContent) msg;

                int i = count.incrementAndGet();

                if(i < 100 || i%1000 == 0 || n - i < 1000) {
                    System.err.print(content.content().toString(CharsetUtil.UTF_8));
                }

                if(i < n){
                    try {
                       if(i == 0) Thread.sleep(100);

                       ctx.writeAndFlush(request);
                    }
                    catch (InterruptedException e) {
                        ctx.close();
                    }
                } else {
                    ctx.close();
                }
            }
        }

        @Override
        public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) {
            cause.printStackTrace();
            ctx.close();
        }
    }


}
