/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.jaxos;

import org.jaxos.app.ClientApp;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        ClientApp classUnderTest = new ClientApp();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
