#!/bin/bash
SERVER="10.135.72.251"

REQ_COUNT=100
PAR_COUNT=5

n=1000000
if [ -n "$1" ]; then
    n="$1"
fi

URL="http://$SERVER:808$1/acquire?key=girl.id"
IGNORE_LEADER_PARAM="&ignoreleader=true"

i=0;
while [ $i -lt $n ]; do
    for url in `cat urls2`; do
	echo
	date
	echo "$url"
	curl "$url"
	ab -q -S -n $REQ_COUNT -c $PAR_COUNT -k -l "$url$IGNORE_LEADER_PARAM"
	# 2>&1 > /dev/null
    done
    echo "================"
    let i=i+1
    sleep 20 
done
