#!/bin/bash
SERVER="10.135.72.251"

n=1000000
if [ -n "$1" ]; then
    n="$1"
fi

URL="http://$SERVER:808$1/acquire?key=girl.id"

i=0;
while [ $i -lt $n ]; do
    for url in `cat urls`; do
	echo
	date
	echo "$url"
	curl "$url"
	ab -n 10 -c 1 -k -l "$url"
    done
    echo "================"
    let i=i+1
    sleep 60 
done
