#!/usr/bin/env sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
##
##  jaxos start up script for UN*X
##
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done
SAVED="`pwd`"
cd "`dirname \"$PRG\"`/.." >/dev/null
APP_HOME="`pwd -P`"

APP_NAME="jaxos"
APP_BASE_NAME=`basename "$0"`

cd $APP_HOME
server_id=$(head $APP_HOME/server_id)

PID=$(jps|grep ServerApp|head -n 1|cut -f 1 -d ' ')

if [ -n "$PID" ]; then
   kill -15 $PID
   echo wait $PID terminated
fi

while [ -n "$PID" ]; do 
   sleep 1
   echo "..."
   PID=$(jps|grep ServerApp|head -n 1|cut -f 1 -d ' ')
done

nohup $APP_HOME/bin/jaxos -i $server_id -f $APP_HOME/jaxos.properties -d $APP_HOME/data -b 32 > $APP_HOME/logs/output.log 2>&1 &

PID=$(jps|grep ServerApp|head -n 1|cut -f 1 -d ' ')

while [ -z "$PID" ]; do
   echo wait jaxos start
   sleep 1

   PID=$(jps|grep ServerApp|head -n 1|cut -f 1 -d ' ')
 done

 echo "New Jaxos started of PID $PID at $server_id"
cd "$SAVED" >/dev/null
