core:
  id: 1
  thread.number: 3
  peer.timeout: 200m
  partition.number: 3

db:
  path: /media/bison/disk1_1/db8
  sync: 2s
  checkpoint.minutes: 7

learn:
  timeout: 5s
  max-instance: 50000
  max-send: 10000

leader:
  lease: 2s
  mandatory: true
  
peers:
  - id: 1
    hostname: localhost
    consensus-port: 9091
    http-port: 8088

tans:
  batch-size: 16

