// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/paxos-msg.proto

package org.jaxos.network.protobuff;

public final class PaxosMessage {
  private PaxosMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code org.jaxos.network.protobuff.Code}
   */
  public enum Code
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NOOP = 0;</code>
     */
    NOOP(0),
    /**
     * <code>HEART_BEAT = 1;</code>
     */
    HEART_BEAT(1),
    /**
     * <code>PREPARE_REQ = 2;</code>
     */
    PREPARE_REQ(2),
    /**
     * <code>PREPARE_RES = 3;</code>
     */
    PREPARE_RES(3),
    /**
     * <code>ACCEPT_REQ = 4;</code>
     */
    ACCEPT_REQ(4),
    /**
     * <code>ACCEPT_RES = 5;</code>
     */
    ACCEPT_RES(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NOOP = 0;</code>
     */
    public static final int NOOP_VALUE = 0;
    /**
     * <code>HEART_BEAT = 1;</code>
     */
    public static final int HEART_BEAT_VALUE = 1;
    /**
     * <code>PREPARE_REQ = 2;</code>
     */
    public static final int PREPARE_REQ_VALUE = 2;
    /**
     * <code>PREPARE_RES = 3;</code>
     */
    public static final int PREPARE_RES_VALUE = 3;
    /**
     * <code>ACCEPT_REQ = 4;</code>
     */
    public static final int ACCEPT_REQ_VALUE = 4;
    /**
     * <code>ACCEPT_RES = 5;</code>
     */
    public static final int ACCEPT_RES_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Code valueOf(int value) {
      return forNumber(value);
    }

    public static Code forNumber(int value) {
      switch (value) {
        case 0: return NOOP;
        case 1: return HEART_BEAT;
        case 2: return PREPARE_REQ;
        case 3: return PREPARE_RES;
        case 4: return ACCEPT_REQ;
        case 5: return ACCEPT_RES;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Code>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Code> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Code>() {
            public Code findValueByNumber(int number) {
              return Code.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.jaxos.network.protobuff.PaxosMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final Code[] VALUES = values();

    public static Code valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Code(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.jaxos.network.protobuff.Code)
  }

  public interface DataGramOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.jaxos.network.protobuff.DataGram)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.org.jaxos.network.protobuff.Code code = 1;</code>
     */
    int getCodeValue();
    /**
     * <code>.org.jaxos.network.protobuff.Code code = 1;</code>
     */
    org.jaxos.network.protobuff.PaxosMessage.Code getCode();

    /**
     * <code>int32 sender = 2;</code>
     */
    int getSender();

    /**
     * <code>int64 instanceId = 3;</code>
     */
    long getInstanceId();

    /**
     * <code>bytes body = 4;</code>
     */
    com.google.protobuf.ByteString getBody();
  }
  /**
   * Protobuf type {@code org.jaxos.network.protobuff.DataGram}
   */
  public  static final class DataGram extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.jaxos.network.protobuff.DataGram)
      DataGramOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DataGram.newBuilder() to construct.
    private DataGram(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataGram() {
      code_ = 0;
      body_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DataGram();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DataGram(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              code_ = rawValue;
              break;
            }
            case 16: {

              sender_ = input.readInt32();
              break;
            }
            case 24: {

              instanceId_ = input.readInt64();
              break;
            }
            case 34: {

              body_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jaxos.network.protobuff.PaxosMessage.internal_static_org_jaxos_network_protobuff_DataGram_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jaxos.network.protobuff.PaxosMessage.internal_static_org_jaxos_network_protobuff_DataGram_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.jaxos.network.protobuff.PaxosMessage.DataGram.class, org.jaxos.network.protobuff.PaxosMessage.DataGram.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>.org.jaxos.network.protobuff.Code code = 1;</code>
     */
    public int getCodeValue() {
      return code_;
    }
    /**
     * <code>.org.jaxos.network.protobuff.Code code = 1;</code>
     */
    public org.jaxos.network.protobuff.PaxosMessage.Code getCode() {
      @SuppressWarnings("deprecation")
      org.jaxos.network.protobuff.PaxosMessage.Code result = org.jaxos.network.protobuff.PaxosMessage.Code.valueOf(code_);
      return result == null ? org.jaxos.network.protobuff.PaxosMessage.Code.UNRECOGNIZED : result;
    }

    public static final int SENDER_FIELD_NUMBER = 2;
    private int sender_;
    /**
     * <code>int32 sender = 2;</code>
     */
    public int getSender() {
      return sender_;
    }

    public static final int INSTANCEID_FIELD_NUMBER = 3;
    private long instanceId_;
    /**
     * <code>int64 instanceId = 3;</code>
     */
    public long getInstanceId() {
      return instanceId_;
    }

    public static final int BODY_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString body_;
    /**
     * <code>bytes body = 4;</code>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != org.jaxos.network.protobuff.PaxosMessage.Code.NOOP.getNumber()) {
        output.writeEnum(1, code_);
      }
      if (sender_ != 0) {
        output.writeInt32(2, sender_);
      }
      if (instanceId_ != 0L) {
        output.writeInt64(3, instanceId_);
      }
      if (!body_.isEmpty()) {
        output.writeBytes(4, body_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != org.jaxos.network.protobuff.PaxosMessage.Code.NOOP.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, code_);
      }
      if (sender_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, sender_);
      }
      if (instanceId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, instanceId_);
      }
      if (!body_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, body_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.jaxos.network.protobuff.PaxosMessage.DataGram)) {
        return super.equals(obj);
      }
      org.jaxos.network.protobuff.PaxosMessage.DataGram other = (org.jaxos.network.protobuff.PaxosMessage.DataGram) obj;

      if (code_ != other.code_) return false;
      if (getSender()
          != other.getSender()) return false;
      if (getInstanceId()
          != other.getInstanceId()) return false;
      if (!getBody()
          .equals(other.getBody())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + code_;
      hash = (37 * hash) + SENDER_FIELD_NUMBER;
      hash = (53 * hash) + getSender();
      hash = (37 * hash) + INSTANCEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getInstanceId());
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.jaxos.network.protobuff.PaxosMessage.DataGram parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.jaxos.network.protobuff.PaxosMessage.DataGram parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.jaxos.network.protobuff.PaxosMessage.DataGram parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.jaxos.network.protobuff.PaxosMessage.DataGram parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.jaxos.network.protobuff.PaxosMessage.DataGram parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.jaxos.network.protobuff.PaxosMessage.DataGram parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.jaxos.network.protobuff.PaxosMessage.DataGram parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.jaxos.network.protobuff.PaxosMessage.DataGram parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.jaxos.network.protobuff.PaxosMessage.DataGram parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.jaxos.network.protobuff.PaxosMessage.DataGram parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.jaxos.network.protobuff.PaxosMessage.DataGram parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.jaxos.network.protobuff.PaxosMessage.DataGram parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.jaxos.network.protobuff.PaxosMessage.DataGram prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.jaxos.network.protobuff.DataGram}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.jaxos.network.protobuff.DataGram)
        org.jaxos.network.protobuff.PaxosMessage.DataGramOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.jaxos.network.protobuff.PaxosMessage.internal_static_org_jaxos_network_protobuff_DataGram_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.jaxos.network.protobuff.PaxosMessage.internal_static_org_jaxos_network_protobuff_DataGram_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.jaxos.network.protobuff.PaxosMessage.DataGram.class, org.jaxos.network.protobuff.PaxosMessage.DataGram.Builder.class);
      }

      // Construct using org.jaxos.network.protobuff.PaxosMessage.DataGram.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        code_ = 0;

        sender_ = 0;

        instanceId_ = 0L;

        body_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.jaxos.network.protobuff.PaxosMessage.internal_static_org_jaxos_network_protobuff_DataGram_descriptor;
      }

      @java.lang.Override
      public org.jaxos.network.protobuff.PaxosMessage.DataGram getDefaultInstanceForType() {
        return org.jaxos.network.protobuff.PaxosMessage.DataGram.getDefaultInstance();
      }

      @java.lang.Override
      public org.jaxos.network.protobuff.PaxosMessage.DataGram build() {
        org.jaxos.network.protobuff.PaxosMessage.DataGram result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.jaxos.network.protobuff.PaxosMessage.DataGram buildPartial() {
        org.jaxos.network.protobuff.PaxosMessage.DataGram result = new org.jaxos.network.protobuff.PaxosMessage.DataGram(this);
        result.code_ = code_;
        result.sender_ = sender_;
        result.instanceId_ = instanceId_;
        result.body_ = body_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.jaxos.network.protobuff.PaxosMessage.DataGram) {
          return mergeFrom((org.jaxos.network.protobuff.PaxosMessage.DataGram)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.jaxos.network.protobuff.PaxosMessage.DataGram other) {
        if (other == org.jaxos.network.protobuff.PaxosMessage.DataGram.getDefaultInstance()) return this;
        if (other.code_ != 0) {
          setCodeValue(other.getCodeValue());
        }
        if (other.getSender() != 0) {
          setSender(other.getSender());
        }
        if (other.getInstanceId() != 0L) {
          setInstanceId(other.getInstanceId());
        }
        if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
          setBody(other.getBody());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.jaxos.network.protobuff.PaxosMessage.DataGram parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.jaxos.network.protobuff.PaxosMessage.DataGram) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int code_ = 0;
      /**
       * <code>.org.jaxos.network.protobuff.Code code = 1;</code>
       */
      public int getCodeValue() {
        return code_;
      }
      /**
       * <code>.org.jaxos.network.protobuff.Code code = 1;</code>
       */
      public Builder setCodeValue(int value) {
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.org.jaxos.network.protobuff.Code code = 1;</code>
       */
      public org.jaxos.network.protobuff.PaxosMessage.Code getCode() {
        @SuppressWarnings("deprecation")
        org.jaxos.network.protobuff.PaxosMessage.Code result = org.jaxos.network.protobuff.PaxosMessage.Code.valueOf(code_);
        return result == null ? org.jaxos.network.protobuff.PaxosMessage.Code.UNRECOGNIZED : result;
      }
      /**
       * <code>.org.jaxos.network.protobuff.Code code = 1;</code>
       */
      public Builder setCode(org.jaxos.network.protobuff.PaxosMessage.Code value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        code_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.org.jaxos.network.protobuff.Code code = 1;</code>
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private int sender_ ;
      /**
       * <code>int32 sender = 2;</code>
       */
      public int getSender() {
        return sender_;
      }
      /**
       * <code>int32 sender = 2;</code>
       */
      public Builder setSender(int value) {
        
        sender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sender = 2;</code>
       */
      public Builder clearSender() {
        
        sender_ = 0;
        onChanged();
        return this;
      }

      private long instanceId_ ;
      /**
       * <code>int64 instanceId = 3;</code>
       */
      public long getInstanceId() {
        return instanceId_;
      }
      /**
       * <code>int64 instanceId = 3;</code>
       */
      public Builder setInstanceId(long value) {
        
        instanceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 instanceId = 3;</code>
       */
      public Builder clearInstanceId() {
        
        instanceId_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes body = 4;</code>
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <code>bytes body = 4;</code>
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes body = 4;</code>
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.jaxos.network.protobuff.DataGram)
    }

    // @@protoc_insertion_point(class_scope:org.jaxos.network.protobuff.DataGram)
    private static final org.jaxos.network.protobuff.PaxosMessage.DataGram DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.jaxos.network.protobuff.PaxosMessage.DataGram();
    }

    public static org.jaxos.network.protobuff.PaxosMessage.DataGram getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DataGram>
        PARSER = new com.google.protobuf.AbstractParser<DataGram>() {
      @java.lang.Override
      public DataGram parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataGram(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DataGram> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DataGram> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.jaxos.network.protobuff.PaxosMessage.DataGram getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PrepareReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.jaxos.network.protobuff.PrepareReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 ballot = 1;</code>
     */
    int getBallot();
  }
  /**
   * Protobuf type {@code org.jaxos.network.protobuff.PrepareReq}
   */
  public  static final class PrepareReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.jaxos.network.protobuff.PrepareReq)
      PrepareReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PrepareReq.newBuilder() to construct.
    private PrepareReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PrepareReq() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PrepareReq();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PrepareReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              ballot_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jaxos.network.protobuff.PaxosMessage.internal_static_org_jaxos_network_protobuff_PrepareReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jaxos.network.protobuff.PaxosMessage.internal_static_org_jaxos_network_protobuff_PrepareReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.jaxos.network.protobuff.PaxosMessage.PrepareReq.class, org.jaxos.network.protobuff.PaxosMessage.PrepareReq.Builder.class);
    }

    public static final int BALLOT_FIELD_NUMBER = 1;
    private int ballot_;
    /**
     * <code>int32 ballot = 1;</code>
     */
    public int getBallot() {
      return ballot_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (ballot_ != 0) {
        output.writeInt32(1, ballot_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (ballot_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, ballot_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.jaxos.network.protobuff.PaxosMessage.PrepareReq)) {
        return super.equals(obj);
      }
      org.jaxos.network.protobuff.PaxosMessage.PrepareReq other = (org.jaxos.network.protobuff.PaxosMessage.PrepareReq) obj;

      if (getBallot()
          != other.getBallot()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BALLOT_FIELD_NUMBER;
      hash = (53 * hash) + getBallot();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.jaxos.network.protobuff.PaxosMessage.PrepareReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.jaxos.network.protobuff.PaxosMessage.PrepareReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.jaxos.network.protobuff.PaxosMessage.PrepareReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.jaxos.network.protobuff.PaxosMessage.PrepareReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.jaxos.network.protobuff.PaxosMessage.PrepareReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.jaxos.network.protobuff.PaxosMessage.PrepareReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.jaxos.network.protobuff.PaxosMessage.PrepareReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.jaxos.network.protobuff.PaxosMessage.PrepareReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.jaxos.network.protobuff.PaxosMessage.PrepareReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.jaxos.network.protobuff.PaxosMessage.PrepareReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.jaxos.network.protobuff.PaxosMessage.PrepareReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.jaxos.network.protobuff.PaxosMessage.PrepareReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.jaxos.network.protobuff.PaxosMessage.PrepareReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.jaxos.network.protobuff.PrepareReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.jaxos.network.protobuff.PrepareReq)
        org.jaxos.network.protobuff.PaxosMessage.PrepareReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.jaxos.network.protobuff.PaxosMessage.internal_static_org_jaxos_network_protobuff_PrepareReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.jaxos.network.protobuff.PaxosMessage.internal_static_org_jaxos_network_protobuff_PrepareReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.jaxos.network.protobuff.PaxosMessage.PrepareReq.class, org.jaxos.network.protobuff.PaxosMessage.PrepareReq.Builder.class);
      }

      // Construct using org.jaxos.network.protobuff.PaxosMessage.PrepareReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        ballot_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.jaxos.network.protobuff.PaxosMessage.internal_static_org_jaxos_network_protobuff_PrepareReq_descriptor;
      }

      @java.lang.Override
      public org.jaxos.network.protobuff.PaxosMessage.PrepareReq getDefaultInstanceForType() {
        return org.jaxos.network.protobuff.PaxosMessage.PrepareReq.getDefaultInstance();
      }

      @java.lang.Override
      public org.jaxos.network.protobuff.PaxosMessage.PrepareReq build() {
        org.jaxos.network.protobuff.PaxosMessage.PrepareReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.jaxos.network.protobuff.PaxosMessage.PrepareReq buildPartial() {
        org.jaxos.network.protobuff.PaxosMessage.PrepareReq result = new org.jaxos.network.protobuff.PaxosMessage.PrepareReq(this);
        result.ballot_ = ballot_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.jaxos.network.protobuff.PaxosMessage.PrepareReq) {
          return mergeFrom((org.jaxos.network.protobuff.PaxosMessage.PrepareReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.jaxos.network.protobuff.PaxosMessage.PrepareReq other) {
        if (other == org.jaxos.network.protobuff.PaxosMessage.PrepareReq.getDefaultInstance()) return this;
        if (other.getBallot() != 0) {
          setBallot(other.getBallot());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.jaxos.network.protobuff.PaxosMessage.PrepareReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.jaxos.network.protobuff.PaxosMessage.PrepareReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int ballot_ ;
      /**
       * <code>int32 ballot = 1;</code>
       */
      public int getBallot() {
        return ballot_;
      }
      /**
       * <code>int32 ballot = 1;</code>
       */
      public Builder setBallot(int value) {
        
        ballot_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 ballot = 1;</code>
       */
      public Builder clearBallot() {
        
        ballot_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.jaxos.network.protobuff.PrepareReq)
    }

    // @@protoc_insertion_point(class_scope:org.jaxos.network.protobuff.PrepareReq)
    private static final org.jaxos.network.protobuff.PaxosMessage.PrepareReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.jaxos.network.protobuff.PaxosMessage.PrepareReq();
    }

    public static org.jaxos.network.protobuff.PaxosMessage.PrepareReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PrepareReq>
        PARSER = new com.google.protobuf.AbstractParser<PrepareReq>() {
      @java.lang.Override
      public PrepareReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PrepareReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PrepareReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PrepareReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.jaxos.network.protobuff.PaxosMessage.PrepareReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PrepareResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.jaxos.network.protobuff.PrepareRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool success = 1;</code>
     */
    boolean getSuccess();

    /**
     * <code>int32 maxBallot = 2;</code>
     */
    int getMaxBallot();

    /**
     * <code>int32 acceptedBallot = 3;</code>
     */
    int getAcceptedBallot();

    /**
     * <code>bytes acceptedValue = 4;</code>
     */
    com.google.protobuf.ByteString getAcceptedValue();
  }
  /**
   * Protobuf type {@code org.jaxos.network.protobuff.PrepareRes}
   */
  public  static final class PrepareRes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.jaxos.network.protobuff.PrepareRes)
      PrepareResOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PrepareRes.newBuilder() to construct.
    private PrepareRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PrepareRes() {
      acceptedValue_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PrepareRes();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PrepareRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              success_ = input.readBool();
              break;
            }
            case 16: {

              maxBallot_ = input.readInt32();
              break;
            }
            case 24: {

              acceptedBallot_ = input.readInt32();
              break;
            }
            case 34: {

              acceptedValue_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jaxos.network.protobuff.PaxosMessage.internal_static_org_jaxos_network_protobuff_PrepareRes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jaxos.network.protobuff.PaxosMessage.internal_static_org_jaxos_network_protobuff_PrepareRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.jaxos.network.protobuff.PaxosMessage.PrepareRes.class, org.jaxos.network.protobuff.PaxosMessage.PrepareRes.Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>bool success = 1;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    public static final int MAXBALLOT_FIELD_NUMBER = 2;
    private int maxBallot_;
    /**
     * <code>int32 maxBallot = 2;</code>
     */
    public int getMaxBallot() {
      return maxBallot_;
    }

    public static final int ACCEPTEDBALLOT_FIELD_NUMBER = 3;
    private int acceptedBallot_;
    /**
     * <code>int32 acceptedBallot = 3;</code>
     */
    public int getAcceptedBallot() {
      return acceptedBallot_;
    }

    public static final int ACCEPTEDVALUE_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString acceptedValue_;
    /**
     * <code>bytes acceptedValue = 4;</code>
     */
    public com.google.protobuf.ByteString getAcceptedValue() {
      return acceptedValue_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      if (maxBallot_ != 0) {
        output.writeInt32(2, maxBallot_);
      }
      if (acceptedBallot_ != 0) {
        output.writeInt32(3, acceptedBallot_);
      }
      if (!acceptedValue_.isEmpty()) {
        output.writeBytes(4, acceptedValue_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      if (maxBallot_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, maxBallot_);
      }
      if (acceptedBallot_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, acceptedBallot_);
      }
      if (!acceptedValue_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, acceptedValue_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.jaxos.network.protobuff.PaxosMessage.PrepareRes)) {
        return super.equals(obj);
      }
      org.jaxos.network.protobuff.PaxosMessage.PrepareRes other = (org.jaxos.network.protobuff.PaxosMessage.PrepareRes) obj;

      if (getSuccess()
          != other.getSuccess()) return false;
      if (getMaxBallot()
          != other.getMaxBallot()) return false;
      if (getAcceptedBallot()
          != other.getAcceptedBallot()) return false;
      if (!getAcceptedValue()
          .equals(other.getAcceptedValue())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (37 * hash) + MAXBALLOT_FIELD_NUMBER;
      hash = (53 * hash) + getMaxBallot();
      hash = (37 * hash) + ACCEPTEDBALLOT_FIELD_NUMBER;
      hash = (53 * hash) + getAcceptedBallot();
      hash = (37 * hash) + ACCEPTEDVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getAcceptedValue().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.jaxos.network.protobuff.PaxosMessage.PrepareRes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.jaxos.network.protobuff.PaxosMessage.PrepareRes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.jaxos.network.protobuff.PaxosMessage.PrepareRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.jaxos.network.protobuff.PaxosMessage.PrepareRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.jaxos.network.protobuff.PaxosMessage.PrepareRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.jaxos.network.protobuff.PaxosMessage.PrepareRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.jaxos.network.protobuff.PaxosMessage.PrepareRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.jaxos.network.protobuff.PaxosMessage.PrepareRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.jaxos.network.protobuff.PaxosMessage.PrepareRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.jaxos.network.protobuff.PaxosMessage.PrepareRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.jaxos.network.protobuff.PaxosMessage.PrepareRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.jaxos.network.protobuff.PaxosMessage.PrepareRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.jaxos.network.protobuff.PaxosMessage.PrepareRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.jaxos.network.protobuff.PrepareRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.jaxos.network.protobuff.PrepareRes)
        org.jaxos.network.protobuff.PaxosMessage.PrepareResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.jaxos.network.protobuff.PaxosMessage.internal_static_org_jaxos_network_protobuff_PrepareRes_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.jaxos.network.protobuff.PaxosMessage.internal_static_org_jaxos_network_protobuff_PrepareRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.jaxos.network.protobuff.PaxosMessage.PrepareRes.class, org.jaxos.network.protobuff.PaxosMessage.PrepareRes.Builder.class);
      }

      // Construct using org.jaxos.network.protobuff.PaxosMessage.PrepareRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        success_ = false;

        maxBallot_ = 0;

        acceptedBallot_ = 0;

        acceptedValue_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.jaxos.network.protobuff.PaxosMessage.internal_static_org_jaxos_network_protobuff_PrepareRes_descriptor;
      }

      @java.lang.Override
      public org.jaxos.network.protobuff.PaxosMessage.PrepareRes getDefaultInstanceForType() {
        return org.jaxos.network.protobuff.PaxosMessage.PrepareRes.getDefaultInstance();
      }

      @java.lang.Override
      public org.jaxos.network.protobuff.PaxosMessage.PrepareRes build() {
        org.jaxos.network.protobuff.PaxosMessage.PrepareRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.jaxos.network.protobuff.PaxosMessage.PrepareRes buildPartial() {
        org.jaxos.network.protobuff.PaxosMessage.PrepareRes result = new org.jaxos.network.protobuff.PaxosMessage.PrepareRes(this);
        result.success_ = success_;
        result.maxBallot_ = maxBallot_;
        result.acceptedBallot_ = acceptedBallot_;
        result.acceptedValue_ = acceptedValue_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.jaxos.network.protobuff.PaxosMessage.PrepareRes) {
          return mergeFrom((org.jaxos.network.protobuff.PaxosMessage.PrepareRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.jaxos.network.protobuff.PaxosMessage.PrepareRes other) {
        if (other == org.jaxos.network.protobuff.PaxosMessage.PrepareRes.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (other.getMaxBallot() != 0) {
          setMaxBallot(other.getMaxBallot());
        }
        if (other.getAcceptedBallot() != 0) {
          setAcceptedBallot(other.getAcceptedBallot());
        }
        if (other.getAcceptedValue() != com.google.protobuf.ByteString.EMPTY) {
          setAcceptedValue(other.getAcceptedValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.jaxos.network.protobuff.PaxosMessage.PrepareRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.jaxos.network.protobuff.PaxosMessage.PrepareRes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean success_ ;
      /**
       * <code>bool success = 1;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool success = 1;</code>
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 1;</code>
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }

      private int maxBallot_ ;
      /**
       * <code>int32 maxBallot = 2;</code>
       */
      public int getMaxBallot() {
        return maxBallot_;
      }
      /**
       * <code>int32 maxBallot = 2;</code>
       */
      public Builder setMaxBallot(int value) {
        
        maxBallot_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 maxBallot = 2;</code>
       */
      public Builder clearMaxBallot() {
        
        maxBallot_ = 0;
        onChanged();
        return this;
      }

      private int acceptedBallot_ ;
      /**
       * <code>int32 acceptedBallot = 3;</code>
       */
      public int getAcceptedBallot() {
        return acceptedBallot_;
      }
      /**
       * <code>int32 acceptedBallot = 3;</code>
       */
      public Builder setAcceptedBallot(int value) {
        
        acceptedBallot_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 acceptedBallot = 3;</code>
       */
      public Builder clearAcceptedBallot() {
        
        acceptedBallot_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString acceptedValue_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes acceptedValue = 4;</code>
       */
      public com.google.protobuf.ByteString getAcceptedValue() {
        return acceptedValue_;
      }
      /**
       * <code>bytes acceptedValue = 4;</code>
       */
      public Builder setAcceptedValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        acceptedValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes acceptedValue = 4;</code>
       */
      public Builder clearAcceptedValue() {
        
        acceptedValue_ = getDefaultInstance().getAcceptedValue();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.jaxos.network.protobuff.PrepareRes)
    }

    // @@protoc_insertion_point(class_scope:org.jaxos.network.protobuff.PrepareRes)
    private static final org.jaxos.network.protobuff.PaxosMessage.PrepareRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.jaxos.network.protobuff.PaxosMessage.PrepareRes();
    }

    public static org.jaxos.network.protobuff.PaxosMessage.PrepareRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PrepareRes>
        PARSER = new com.google.protobuf.AbstractParser<PrepareRes>() {
      @java.lang.Override
      public PrepareRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PrepareRes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PrepareRes> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PrepareRes> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.jaxos.network.protobuff.PaxosMessage.PrepareRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_jaxos_network_protobuff_DataGram_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_jaxos_network_protobuff_DataGram_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_jaxos_network_protobuff_PrepareReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_jaxos_network_protobuff_PrepareReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_jaxos_network_protobuff_PrepareRes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_jaxos_network_protobuff_PrepareRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025proto/paxos-msg.proto\022\033org.jaxos.netwo" +
      "rk.protobuff\"m\n\010DataGram\022/\n\004code\030\001 \001(\0162!" +
      ".org.jaxos.network.protobuff.Code\022\016\n\006sen" +
      "der\030\002 \001(\005\022\022\n\ninstanceId\030\003 \001(\003\022\014\n\004body\030\004 " +
      "\001(\014\"\034\n\nPrepareReq\022\016\n\006ballot\030\001 \001(\005\"_\n\nPre" +
      "pareRes\022\017\n\007success\030\001 \001(\010\022\021\n\tmaxBallot\030\002 " +
      "\001(\005\022\026\n\016acceptedBallot\030\003 \001(\005\022\025\n\racceptedV" +
      "alue\030\004 \001(\014*b\n\004Code\022\010\n\004NOOP\020\000\022\016\n\nHEART_BE" +
      "AT\020\001\022\017\n\013PREPARE_REQ\020\002\022\017\n\013PREPARE_RES\020\003\022\016" +
      "\n\nACCEPT_REQ\020\004\022\016\n\nACCEPT_RES\020\005B\016B\014PaxosM" +
      "essageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_jaxos_network_protobuff_DataGram_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_jaxos_network_protobuff_DataGram_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_jaxos_network_protobuff_DataGram_descriptor,
        new java.lang.String[] { "Code", "Sender", "InstanceId", "Body", });
    internal_static_org_jaxos_network_protobuff_PrepareReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_jaxos_network_protobuff_PrepareReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_jaxos_network_protobuff_PrepareReq_descriptor,
        new java.lang.String[] { "Ballot", });
    internal_static_org_jaxos_network_protobuff_PrepareRes_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_jaxos_network_protobuff_PrepareRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_jaxos_network_protobuff_PrepareRes_descriptor,
        new java.lang.String[] { "Success", "MaxBallot", "AcceptedBallot", "AcceptedValue", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
